#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SFUAndroid.Resource", IsApplication=true)]

namespace SFUAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int search_bg_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sfulogo = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int BookImage = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int BookName = 2131165185;
			
			// aapt resource value: 0x7f070011
			public const int BooksButton = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int BooksListView = 2131165186;
			
			// aapt resource value: 0x7f070014
			public const int BurnabyMapButton = 2131165204;
			
			// aapt resource value: 0x7f07001b
			public const int BusRoutesListView = 2131165211;
			
			// aapt resource value: 0x7f070008
			public const int ComputingIdLabel = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int ComputingIdText = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int CourseInstructor = 2131165191;
			
			// aapt resource value: 0x7f07001a
			public const int CourseListView = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int CourseName = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int CourseSection = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int HarbourCentreMapButton = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int LoginButton = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int LoginProgressBar = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int LoginUserButton = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int MapsButton = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int PasswordLabel = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int PasswordText = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int ProtectedServicesButton = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int RouteName = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int RouteTimes = 2131165188;
			
			// aapt resource value: 0x7f070010
			public const int ScheduleButton = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int ScheduleScrollView = 2131165209;
			
			// aapt resource value: 0x7f070015
			public const int SurreyMapButton = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int TransitButton = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int listview = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int ps_webView = 2131165208;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int config_slide_time = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Book = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Books = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BusRoute = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Course = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Maps = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ProtectedServices = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProtectedServicesBrowser = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Schedule = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int slide_up_left = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int slide_up_right = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SurreyFloorSelect = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Transit = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050008
			public const int ApplicationName = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int Books = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int ComputingId = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int Courses = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Library = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int Login = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int Maps = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int Password = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ProtectedServices = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int Schedule = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int Transit = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int nowCardStyle = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
