#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SFUAndroid.Resource", IsApplication=true)]

namespace SFUAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080001
			public const int burnaby_buildings_array = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int surrey_floors_array = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int goblinGreen = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int lvDividerColor = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int lvHeaderDividerColor = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int lvHeaderTextColor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryTextColor = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int secondaryTextColor = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f05000c
			public const int lvDividerHeight = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int lvDividerMargin = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int lvDividerWidth = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int lvHdrItemHeight = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int lvHeadingPaddingLeft = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int lvHeadingTextSize = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int lvItemHeight = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int lvPrimaryPaddingBottom = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int lvPrimaryPaddingLeft = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int lvPrimaryPaddingTop = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int lvPrimaryTextSize = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int lvSecondaryPaddingBottom = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int lvSecondaryPaddingLeft = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int lvSecondaryPaddingTop = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int lvSecondaryTextSize = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int lvSectionDividerMargin = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int lvSectionDividerMarginTop = 2131034128;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int books = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int books2x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int card_bg2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int courses = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int courses2x = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_refresh = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_user = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_details = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int important = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int library = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int library2x = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int maps = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int maps2x = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int proserv = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int proserv2x = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int search_bg_shadow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sfulogo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int transit = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int transit2x = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int wht8c = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0005
			public const int BooksListView = 2131427333;
			
			// aapt resource value: 0x7f0b0016
			public const int BurnabyBuildingSpinner = 2131427350;
			
			// aapt resource value: 0x7f0b001b
			public const int BusRoutesListView = 2131427355;
			
			// aapt resource value: 0x7f0b000b
			public const int ClassTimeListView = 2131427339;
			
			// aapt resource value: 0x7f0b000d
			public const int ComputingIdLabel = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int ComputingIdText = 2131427342;
			
			// aapt resource value: 0x7f0b000a
			public const int CourseInstructor = 2131427338;
			
			// aapt resource value: 0x7f0b001a
			public const int CourseListView = 2131427354;
			
			// aapt resource value: 0x7f0b0008
			public const int CourseName = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int CourseSection = 2131427337;
			
			// aapt resource value: 0x7f0b0012
			public const int LoginProgressBar = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int LoginUserButton = 2131427345;
			
			// aapt resource value: 0x7f0b0014
			public const int MainSelectionButton = 2131427348;
			
			// aapt resource value: 0x7f0b000f
			public const int PasswordLabel = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int PasswordText = 2131427344;
			
			// aapt resource value: 0x7f0b0006
			public const int RouteName = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int RouteTimes = 2131427335;
			
			// aapt resource value: 0x7f0b0019
			public const int ScheduleScrollView = 2131427353;
			
			// aapt resource value: 0x7f0b0015
			public const int SurreyFloorSpinner = 2131427349;
			
			// aapt resource value: 0x7f0b001c
			public const int action_login = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int action_refresh = 2131427357;
			
			// aapt resource value: 0x7f0b0001
			public const int button = 2131427329;
			
			// aapt resource value: 0x7f0b0013
			public const int gridView1 = 2131427347;
			
			// aapt resource value: 0x7f0b0000
			public const int item_separator = 2131427328;
			
			// aapt resource value: 0x7f0b0017
			public const int listview = 2131427351;
			
			// aapt resource value: 0x7f0b0003
			public const int lv_item_header = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int lv_item_subtext = 2131427332;
			
			// aapt resource value: 0x7f0b000c
			public const int lv_list_hdr = 2131427340;
			
			// aapt resource value: 0x7f0b0018
			public const int ps_webView = 2131427352;
			
			// aapt resource value: 0x7f0b0002
			public const int vertical_divider = 2131427330;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int config_slide_time = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Book = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Books = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BusRoute = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Course = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListViewAlignRight = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListViewHeader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MainActivityOption = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Maps = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ProtectedServices = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ProtectedServicesBrowser = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Schedule = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int slide_up_left = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int slide_up_right = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SurreyFloorSelect = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Transit = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main_activity_actions = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int schedule_activity_actions = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int transit_activity_actions = 2131361794;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070008
			public const int ApplicationName = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int Books = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int ComputingId = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int Courses = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Library = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int Login = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int Maps = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int Password = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int ProtectedServices = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int Schedule = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int Transit = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int action_schedule_refresh = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int action_tab_burnaby = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int action_tab_surrey = 2131165197;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppBaseTheme = 2131296256;
			
			// aapt resource value: 0x7f09000a
			public const int CustomActionBar = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int listViewHeaderItem = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int listViewHeaderItemButtonStyle = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int listViewItem = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int listViewItemButtonStyle = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int listViewPrimaryDetail = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int listViewSecondaryDetail = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int listViewSectionDividerVerticalDivider = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int listViewVerticalDivider = 2131296261;
			
			// aapt resource value: 0x7f090009
			public const int nowCardStyle = 2131296265;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
