#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SFUAndroid.Resource", IsApplication=true)]

namespace SFUAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090001
			public const int burnaby_buildings_array = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int surrey_floors_array = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040007
			public const int card_border = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int card_grid_text = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int card_light_text = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int card_separator = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int card_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int card_title_text = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int goblinGreen = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int lvDividerColor = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int lvHeaderDividerColor = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int lvHeaderTextColor = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int primaryTextColor = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int secondaryTextColor = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int stroke = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int text_light = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050044
			public const int action_bar_switch_padding = 2131034180;
			
			// aapt resource value: 0x7f050064
			public const int action_confirm_button_margin = 2131034212;
			
			// aapt resource value: 0x7f05007f
			public const int app_icon_area_height = 2131034239;
			
			// aapt resource value: 0x7f05007e
			public const int app_icon_area_width = 2131034238;
			
			// aapt resource value: 0x7f050027
			public const int at_place_card_content_height = 2131034151;
			
			// aapt resource value: 0x7f05002b
			public const int auto_scroll_padding = 2131034155;
			
			// aapt resource value: 0x7f0500a0
			public const int card_action_button_height = 2131034272;
			
			// aapt resource value: 0x7f050097
			public const int card_action_small_text = 2131034263;
			
			// aapt resource value: 0x7f050098
			public const int card_action_text = 2131034264;
			
			// aapt resource value: 0x7f050091
			public const int card_grid_font_size = 2131034257;
			
			// aapt resource value: 0x7f05009e
			public const int card_horizontal_map_height = 2131034270;
			
			// aapt resource value: 0x7f050094
			public const int card_large_text = 2131034260;
			
			// aapt resource value: 0x7f050095
			public const int card_medium_text = 2131034261;
			
			// aapt resource value: 0x7f050066
			public const int card_minimum_padding = 2131034214;
			
			// aapt resource value: 0x7f050099
			public const int card_padding = 2131034265;
			
			// aapt resource value: 0x7f0500a1
			public const int card_small_padding = 2131034273;
			
			// aapt resource value: 0x7f050096
			public const int card_small_text = 2131034262;
			
			// aapt resource value: 0x7f0500a2
			public const int card_spacer_margin = 2131034274;
			
			// aapt resource value: 0x7f050092
			public const int card_temperature_size = 2131034258;
			
			// aapt resource value: 0x7f050093
			public const int card_xl_text = 2131034259;
			
			// aapt resource value: 0x7f050026
			public const int cards_max_column_width = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int cards_padding_inbetween = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int cards_padding_inbetween_adjusted = 2131034149;
			
			// aapt resource value: 0x7f050080
			public const int contact_avatar_height = 2131034240;
			
			// aapt resource value: 0x7f050081
			public const int contact_avatar_width = 2131034241;
			
			// aapt resource value: 0x7f050082
			public const int contact_select_fragment_padding = 2131034242;
			
			// aapt resource value: 0x7f05004d
			public const int context_header_padding = 2131034189;
			
			// aapt resource value: 0x7f05002f
			public const int control_size = 2131034159;
			
			// aapt resource value: 0x7f05001e
			public const int corpus_bar_left_padding = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int corpus_bar_more_padding = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int corpus_bar_vertical_padding = 2131034141;
			
			// aapt resource value: 0x7f050022
			public const int corpus_selector_element_margin = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int corpus_selector_horizontal_margin = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int corpus_selector_text_size = 2131034145;
			
			// aapt resource value: 0x7f050051
			public const int correction_popup_width_1buttons = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int correction_popup_width_2buttons = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int correction_popup_width_3buttons = 2131034195;
			
			// aapt resource value: 0x7f050056
			public const int dialog_corner_radius = 2131034198;
			
			// aapt resource value: 0x7f050058
			public const int dialog_height = 2131034200;
			
			// aapt resource value: 0x7f05005a
			public const int dialog_pos_left = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int dialog_pos_top = 2131034203;
			
			// aapt resource value: 0x7f050060
			public const int dialog_text_size = 2131034208;
			
			// aapt resource value: 0x7f050057
			public const int dialog_width = 2131034199;
			
			// aapt resource value: 0x7f05005e
			public const int divider_height = 2131034206;
			
			// aapt resource value: 0x7f050015
			public const int extra_height_to_account_for_system_space_in_landscape = 2131034133;
			
			// aapt resource value: 0x7f050023
			public const int first_run_context_image_height = 2131034147;
			
			// aapt resource value: 0x7f05009a
			public const int first_run_padding = 2131034266;
			
			// aapt resource value: 0x7f05001b
			public const int footer_height = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int gmail_card_button_height = 2131034140;
			
			// aapt resource value: 0x7f050016
			public const int google_header_margin_bottom = 2131034134;
			
			// aapt resource value: 0x7f050033
			public const int google_logo_margin_left = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int google_logo_margin_right = 2131034164;
			
			// aapt resource value: 0x7f050070
			public const int half_unit = 2131034224;
			
			// aapt resource value: 0x7f050086
			public const int hands_free_padding = 2131034246;
			
			// aapt resource value: 0x7f050085
			public const int hands_free_small_padding = 2131034245;
			
			// aapt resource value: 0x7f05005f
			public const int header_footer_size = 2131034207;
			
			// aapt resource value: 0x7f05006b
			public const int high_confidence_answer_card_image_height = 2131034219;
			
			// aapt resource value: 0x7f05006c
			public const int high_confidence_answer_card_image_width = 2131034220;
			
			// aapt resource value: 0x7f05006a
			public const int high_confidence_answer_card_min_spacing = 2131034218;
			
			// aapt resource value: 0x7f050055
			public const int hint_bubble_offset = 2131034197;
			
			// aapt resource value: 0x7f0500aa
			public const int histogram_bar_padding = 2131034282;
			
			// aapt resource value: 0x7f0500a9
			public const int histogram_bar_size = 2131034281;
			
			// aapt resource value: 0x7f0500ab
			public const int histogram_width = 2131034283;
			
			// aapt resource value: 0x7f05009f
			public const int horizontal_static_map_height = 2131034271;
			
			// aapt resource value: 0x7f050043
			public const int image_result_carousel_height = 2131034179;
			
			// aapt resource value: 0x7f050042
			public const int image_result_height = 2131034178;
			
			// aapt resource value: 0x7f050037
			public const int image_view_padding = 2131034167;
			
			// aapt resource value: 0x7f05008c
			public const int ime_button_text_size = 2131034252;
			
			// aapt resource value: 0x7f050088
			public const int ime_land_height = 2131034248;
			
			// aapt resource value: 0x7f05008d
			public const int ime_mic_size = 2131034253;
			
			// aapt resource value: 0x7f05008e
			public const int ime_padding_bottom = 2131034254;
			
			// aapt resource value: 0x7f05008f
			public const int ime_padding_top = 2131034255;
			
			// aapt resource value: 0x7f050087
			public const int ime_port_height = 2131034247;
			
			// aapt resource value: 0x7f050089
			public const int ime_spinner_text = 2131034249;
			
			// aapt resource value: 0x7f05008b
			public const int ime_state_text_size = 2131034251;
			
			// aapt resource value: 0x7f05008a
			public const int ime_title_text_size = 2131034250;
			
			// aapt resource value: 0x7f05005c
			public const int indicator_size = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int indicator_stroke = 2131034205;
			
			// aapt resource value: 0x7f050090
			public const int intent_api_mic_area_size = 2131034256;
			
			// aapt resource value: 0x7f050028
			public const int large_preview_width = 2131034152;
			
			// aapt resource value: 0x7f0500a3
			public const int load_more_button_margin = 2131034275;
			
			// aapt resource value: 0x7f05006d
			public const int local_result_vertical_divider_height = 2131034221;
			
			// aapt resource value: 0x7f05006e
			public const int local_results_item_margin = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int local_results_map_height = 2131034223;
			
			// aapt resource value: 0x7f0500b8
			public const int lvDividerHeight = 2131034296;
			
			// aapt resource value: 0x7f0500b9
			public const int lvDividerMargin = 2131034297;
			
			// aapt resource value: 0x7f0500bb
			public const int lvDividerWidth = 2131034299;
			
			// aapt resource value: 0x7f0500ae
			public const int lvHdrItemHeight = 2131034286;
			
			// aapt resource value: 0x7f0500b0
			public const int lvHeadingPaddingLeft = 2131034288;
			
			// aapt resource value: 0x7f0500b1
			public const int lvHeadingTextSize = 2131034289;
			
			// aapt resource value: 0x7f0500af
			public const int lvItemHeight = 2131034287;
			
			// aapt resource value: 0x7f0500b3
			public const int lvPrimaryPaddingBottom = 2131034291;
			
			// aapt resource value: 0x7f0500b4
			public const int lvPrimaryPaddingLeft = 2131034292;
			
			// aapt resource value: 0x7f0500b2
			public const int lvPrimaryPaddingTop = 2131034290;
			
			// aapt resource value: 0x7f0500ac
			public const int lvPrimaryTextSize = 2131034284;
			
			// aapt resource value: 0x7f0500b6
			public const int lvSecondaryPaddingBottom = 2131034294;
			
			// aapt resource value: 0x7f0500b7
			public const int lvSecondaryPaddingLeft = 2131034295;
			
			// aapt resource value: 0x7f0500b5
			public const int lvSecondaryPaddingTop = 2131034293;
			
			// aapt resource value: 0x7f0500ad
			public const int lvSecondaryTextSize = 2131034285;
			
			// aapt resource value: 0x7f0500ba
			public const int lvSectionDividerMargin = 2131034298;
			
			// aapt resource value: 0x7f0500bc
			public const int lvSectionDividerMarginTop = 2131034300;
			
			// aapt resource value: 0x7f050013
			public const int main_fragment_top_padding = 2131034131;
			
			// aapt resource value: 0x7f050069
			public const int map_preview_image_height = 2131034217;
			
			// aapt resource value: 0x7f050068
			public const int map_preview_image_width = 2131034216;
			
			// aapt resource value: 0x7f050059
			public const int max_height_for_fullscreen = 2131034201;
			
			// aapt resource value: 0x7f05002d
			public const int max_preview_area_width = 2131034157;
			
			// aapt resource value: 0x7f050061
			public const int max_waveform_height = 2131034209;
			
			// aapt resource value: 0x7f050063
			public const int mic_height = 2131034211;
			
			// aapt resource value: 0x7f05004c
			public const int min_height_background_image = 2131034188;
			
			// aapt resource value: 0x7f05002c
			public const int min_preview_area_width = 2131034156;
			
			// aapt resource value: 0x7f050075
			public const int negative_unit = 2131034229;
			
			// aapt resource value: 0x7f050002
			public const int photo_crop_stroke_width = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int photo_crop_width = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int photo_preview_size = 2131034115;
			
			// aapt resource value: 0x7f050031
			public const int playpausebutton_size = 2131034161;
			
			// aapt resource value: 0x7f05002a
			public const int preview_image_height = 2131034154;
			
			// aapt resource value: 0x7f050067
			public const int preview_image_size = 2131034215;
			
			// aapt resource value: 0x7f050029
			public const int preview_image_width = 2131034153;
			
			// aapt resource value: 0x7f050054
			public const int recording_popup_size = 2131034196;
			
			// aapt resource value: 0x7f050004
			public const int retry_button_size = 2131034116;
			
			// aapt resource value: 0x7f0500a4
			public const int sample_card_width = 2131034276;
			
			// aapt resource value: 0x7f050050
			public const int searchResultListItemHeight = 2131034192;
			
			// aapt resource value: 0x7f050038
			public const int search_bar_padding = 2131034168;
			
			// aapt resource value: 0x7f050035
			public const int search_bar_text_size = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int search_box_width = 2131034166;
			
			// aapt resource value: 0x7f050008
			public const int search_device_footer_bottom_margin = 2131034120;
			
			// aapt resource value: 0x7f05007a
			public const int search_plate_expand_threshold = 2131034234;
			
			// aapt resource value: 0x7f050032
			public const int search_plate_height = 2131034162;
			
			// aapt resource value: 0x7f05007d
			public const int search_plate_icon_height = 2131034237;
			
			// aapt resource value: 0x7f05007c
			public const int search_plate_icon_width = 2131034236;
			
			// aapt resource value: 0x7f05007b
			public const int search_plate_minimum_padding = 2131034235;
			
			// aapt resource value: 0x7f050076
			public const int small_unit = 2131034230;
			
			// aapt resource value: 0x7f050077
			public const int small_units_2 = 2131034231;
			
			// aapt resource value: 0x7f050078
			public const int small_units_3 = 2131034232;
			
			// aapt resource value: 0x7f050079
			public const int small_units_4 = 2131034233;
			
			// aapt resource value: 0x7f05004b
			public const int speak_now_speech_height = 2131034187;
			
			// aapt resource value: 0x7f050084
			public const int sports_card_image_height = 2131034244;
			
			// aapt resource value: 0x7f050083
			public const int sports_card_image_width = 2131034243;
			
			// aapt resource value: 0x7f050000
			public const int sticky_height = 2131034112;
			
			// aapt resource value: 0x7f0500a7
			public const int stock_chart_height = 2131034279;
			
			// aapt resource value: 0x7f0500a8
			public const int stock_chart_width = 2131034280;
			
			// aapt resource value: 0x7f0500a6
			public const int stock_price_padding = 2131034278;
			
			// aapt resource value: 0x7f050039
			public const int suggest_summons_area_padding = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int suggest_web_height = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int suggest_web_padding = 2131034171;
			
			// aapt resource value: 0x7f050007
			public const int suggestion_footer_view_height = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int suggestion_icon1_left_padding = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int suggestion_icon_size = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int suggestion_large_image_max_height = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int suggestion_large_image_max_width = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int suggestion_text2_height = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int suggestion_text_padding = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int suggestion_view_height = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int suggestion_view_height_large = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int suggestions_divider_margin_left_right = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int suggestions_padding = 2131034129;
			
			// aapt resource value: 0x7f05003c
			public const int summons_height = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int summons_inter_source_padding = 2131034175;
			
			// aapt resource value: 0x7f05003d
			public const int summons_padding = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int summons_width = 2131034174;
			
			// aapt resource value: 0x7f050040
			public const int suppressed_web_results_min_visible_height = 2131034176;
			
			// aapt resource value: 0x7f0500a5
			public const int table_row_vertical_padding = 2131034277;
			
			// aapt resource value: 0x7f05009c
			public const int text_block_bottom_padding = 2131034268;
			
			// aapt resource value: 0x7f05009d
			public const int text_block_side_padding = 2131034269;
			
			// aapt resource value: 0x7f05009b
			public const int text_block_top_padding = 2131034267;
			
			// aapt resource value: 0x7f05002e
			public const int tidbit_padding = 2131034158;
			
			// aapt resource value: 0x7f050071
			public const int unit = 2131034225;
			
			// aapt resource value: 0x7f050065
			public const int unit_small_caps = 2131034213;
			
			// aapt resource value: 0x7f050072
			public const int units_2 = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int units_3 = 2131034227;
			
			// aapt resource value: 0x7f050074
			public const int units_4 = 2131034228;
			
			// aapt resource value: 0x7f050062
			public const int voice_popup_margin = 2131034210;
			
			// aapt resource value: 0x7f05004f
			public const int weather_current_icon_height = 2131034191;
			
			// aapt resource value: 0x7f05004e
			public const int weather_forecast_icon_height = 2131034190;
			
			// aapt resource value: 0x7f050046
			public const int web_snapshots_default_visible_width = 2131034182;
			
			// aapt resource value: 0x7f05004a
			public const int web_snapshots_dismiss_from_offset = 2131034186;
			
			// aapt resource value: 0x7f050048
			public const int web_snapshots_just_added_extra_height = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int web_snapshots_launch_browser_from_offset = 2131034185;
			
			// aapt resource value: 0x7f050047
			public const int web_snapshots_text_size = 2131034183;
			
			// aapt resource value: 0x7f050045
			public const int web_snapshots_width = 2131034181;
			
			// aapt resource value: 0x7f050006
			public const int web_suggestion_icon_size = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int web_suggestion_view_height = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int websearch_card_top_margin = 2131034132;
			
			// aapt resource value: 0x7f050041
			public const int websearch_collapse_card_padding_offscreen_leeway = 2131034177;
			
			// aapt resource value: 0x7f050017
			public const int websearch_fragment_inbetween_padding = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int websearch_header_left_padding = 2131034136;
			
			// aapt resource value: 0x7f050030
			public const int webview_margin_left = 2131034160;
			
			// aapt resource value: 0x7f050019
			public const int widget_margin_left_right = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int widget_margin_top_bottom = 2131034138;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int books = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int books2x = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Campus_Guide_Galleria_3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Campus_Guide_Galleria_4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Campus_Guide_Galleria_5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Campus_Guide_Podium_2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int card = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int card_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int card_background_shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int card_bg2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int card_shadow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int courses = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int courses2x = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_cancel = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_action_refresh = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_action_user = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_details = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_launcher = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int important = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int library = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int library2x = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int maps = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int maps2x = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int pin = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int proserv = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int proserv2x = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int search_bg_shadow = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int selectable_background_cardbank = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int sfu_campus_mapscaled = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int top_shadow = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int transit = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int transit2x = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0005
			public const int BooksListView = 2131427333;
			
			// aapt resource value: 0x7f0b0022
			public const int BurnabyBuildingSpinner = 2131427362;
			
			// aapt resource value: 0x7f0b0006
			public const int BurnabyCampusImageView = 2131427334;
			
			// aapt resource value: 0x7f0b0028
			public const int BusRoutesListView = 2131427368;
			
			// aapt resource value: 0x7f0b0012
			public const int ClassTimeListView = 2131427346;
			
			// aapt resource value: 0x7f0b001a
			public const int ComputingIdLabel = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int ComputingIdText = 2131427355;
			
			// aapt resource value: 0x7f0b0011
			public const int CourseInstructor = 2131427345;
			
			// aapt resource value: 0x7f0b000f
			public const int CourseName = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int CourseSection = 2131427344;
			
			// aapt resource value: 0x7f0b001e
			public const int LoginUserButton = 2131427358;
			
			// aapt resource value: 0x7f0b0020
			public const int MainSelectionButton = 2131427360;
			
			// aapt resource value: 0x7f0b001c
			public const int PasswordLabel = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int PasswordText = 2131427357;
			
			// aapt resource value: 0x7f0b0007
			public const int RouteName = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int RouteTimes = 2131427336;
			
			// aapt resource value: 0x7f0b000d
			public const int ScrollView1 = 2131427341;
			
			// aapt resource value: 0x7f0b0026
			public const int SurreyCampusImageView = 2131427366;
			
			// aapt resource value: 0x7f0b0021
			public const int SurreyFloorSpinner = 2131427361;
			
			// aapt resource value: 0x7f0b0027
			public const int SurreyRoomListView = 2131427367;
			
			// aapt resource value: 0x7f0b0029
			public const int action_login = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public const int action_refresh = 2131427370;
			
			// aapt resource value: 0x7f0b0001
			public const int button = 2131427329;
			
			// aapt resource value: 0x7f0b0015
			public const int cardContent = 2131427349;
			
			// aapt resource value: 0x7f0b0025
			public const int cardsview = 2131427365;
			
			// aapt resource value: 0x7f0b000a
			public const int description = 2131427338;
			
			// aapt resource value: 0x7f0b0013
			public const int footer = 2131427347;
			
			// aapt resource value: 0x7f0b001f
			public const int gridView1 = 2131427359;
			
			// aapt resource value: 0x7f0b0000
			public const int item_separator = 2131427328;
			
			// aapt resource value: 0x7f0b000b
			public const int listView = 2131427339;
			
			// aapt resource value: 0x7f0b0023
			public const int listview = 2131427363;
			
			// aapt resource value: 0x7f0b0003
			public const int lv_item_header = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int lv_item_subtext = 2131427332;
			
			// aapt resource value: 0x7f0b0019
			public const int lv_list_hdr = 2131427353;
			
			// aapt resource value: 0x7f0b0014
			public const int placeholder = 2131427348;
			
			// aapt resource value: 0x7f0b0024
			public const int ps_webView = 2131427364;
			
			// aapt resource value: 0x7f0b0018
			public const int stackContainer = 2131427352;
			
			// aapt resource value: 0x7f0b0016
			public const int stackRoot = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int stackTitle = 2131427351;
			
			// aapt resource value: 0x7f0b000c
			public const int sticky = 2131427340;
			
			// aapt resource value: 0x7f0b000e
			public const int tableLayout = 2131427342;
			
			// aapt resource value: 0x7f0b0009
			public const int title = 2131427337;
			
			// aapt resource value: 0x7f0b0002
			public const int vertical_divider = 2131427330;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int config_slide_time = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Book = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Books = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BurnabyCampusView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BusRoute = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int card_ex = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int cards_view = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int cards_view_multicolumn = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Course = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int footer_fragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int header = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int item_card = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int item_card_empty_first = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int item_card_empty_last = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int item_play_card_empty_first = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int item_stack = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ListView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ListViewAlignRight = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ListViewHeader = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Login = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Main = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int MainActivityOption = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Maps = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ProtectedServices = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int ProtectedServicesBrowser = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Schedule = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int slide_up_left = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int slide_up_right = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int SurreyCampusView = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int SurreyFloorSelect = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Transit = 2130903069;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int main_activity_actions = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int schedule_activity_actions = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int transit_activity_actions = 2131361794;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080008
			public const int ApplicationName = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int Books = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int ComputingId = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int Courses = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Library = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int Login = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int Maps = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int Password = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int ProtectedServices = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int Schedule = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int Transit = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int action_schedule_refresh = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int action_tab_burnaby = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int action_tab_surrey = 2131230733;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060008
			public const int AppBaseTheme = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int CardLightText = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CardText = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int CardTitle = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardTitleBold = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int CustomActionBar = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int Item = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int Item_Sticky = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int Item_Top = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int StackTitle = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int listViewHeaderItem = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int listViewHeaderItemButtonStyle = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int listViewItem = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int listViewItemButtonStyle = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int listViewPrimaryDetail = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int listViewSecondaryDetail = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int listViewSectionDividerVerticalDivider = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int listViewVerticalDivider = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int nowCardStyle = 2131099665;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
